// Customers Feature Components Barrel Export
export { CustomerCard } from './CustomerCard';
export { CustomerDetailModal } from './CustomerDetailModal';
export { CustomerFilters } from './CustomerFilters';
export { CustomerForm } from './CustomerForm';
export { CustomerGrid } from './CustomerGrid';
export { CustomerInsights } from './CustomerInsights';
export { CustomerRow } from './CustomerRow';
export { CustomerSegmentBadge } from './CustomerSegmentBadge';
export { CustomerStats } from './CustomerStats';
export { CustomerTable } from './CustomerTable';
export { Customers } from './Customers';
export { CustomersNew } from './CustomersNew';
export { CrmDashboard } from './CrmDashboard';
export { CustomerTagManager } from './CustomerTagManager';
export { CustomerTagDisplay } from './CustomerTagDisplay';
export { GoogleMapsPlaceholder } from './GoogleMapsPlaceholder';
export { N8NPlaceholder } from './N8NPlaceholder';
export { AutomationCenter } from './AutomationCenter';
export { BirthdayCalendar } from './BirthdayCalendar';
export { CustomerProfile } from './CustomerProfile';

// UI Components moved from /ui/
export { CustomerActivity } from './customer-activity';
export { CustomerList } from './customer-list';
export { CustomerOpportunities } from './customer-opportunities';
export { CustomerSegments } from './customer-segments';
// CustomerStats já exportado acima na linha 10
export { CustomerTrends } from './customer-trends';
export { ProfileCompletenessIndicator } from './profile-completeness';